apiVersion: v1
kind: Service
metadata:
  name: nagp-database-service
spec:
  selector:
    app: database-deployment-persistent
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306