apiVersion: v1
kind: Service
metadata:
  name: nagp-app-node-service
spec:
  type: LoadBalancer
  selector:
    app: nagp-app-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
