apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nagp-database-persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard